# Ignore OLD code
# import requests
# url = "https://inspirehep.net/api/literature?sort=mostrecent&size=250&page=1&q=a Guillermo.Fidalgo.1&format=bibtex"
# inspire = requests.get(url).text


# New code (Super slow)

# test script from GPT
import requests
import time

# Base search endpoint
url = "https://inspirehep.net/api/literature"
query = "a Guillermo.Fidalgo.1"

params = {
    "sort": "mostrecent",
    "size": 50,  # Lower size ensures the backend won't give a 502
    "page": 1,
    "q": query
}

all_bibtex = ""

while True:
    print(f"Querying page {params['page']} for JSON index...")
    response = requests.get(url, params=params)

    if response.status_code != 200:
        print(f"Error {response.status_code} while fetching records.")
        break

    data = response.json()
    hits = data.get('hits', {}).get('hits', [])

    # Stop looping if no more search results return
    if not hits:
        print("Completed processing all pages.")
        break

    print(f"Extracting BibTeX for {len(hits)} papers on this page...")
    for hit in hits:
        # Extract the specialized BibTeX link generated by INSPIRE
        links = hit.get('links', {})
        bibtex_url = links.get('bibtex')

        if bibtex_url:
            try:
                # This fetches the raw pre-compiled string for the single record
                bib_response = requests.get(bibtex_url)
                if bib_response.status_code == 200:
                    all_bibtex += bib_response.text + "\n"
                else:
                    print(f" Failed to get BibTeX for record {hit.get('id')}")
            except Exception as e:
                print(f" Request failed for record {hit.get('id')}: {e}")

            # Respect the API speed limit (15 requests per 5 seconds)
            time.sleep(1) 

    # Advance to the next page of the search index
    params['page'] += 1


zenodo = r"""
@misc{alexander_moreno_briceno_2022_7115834,
  author       = {Alexander Moreno Briceño and Aman Goel and Guillermo Antonio Fidalgo Rodriguez},
  title        = {Teaching Python the Sustainable Way: Lessons Learned at HSF Training},
  month        = sep,
  year         = 2022,
  publisher    = {Zenodo},
  doi          = {10.5281/zenodo.7115834},
  url          = {https://doi.org/10.5281/zenodo.7115834}
}
"""

# Write everything out to a .bib file
if all_bibtex:
    with open("latex_files/bibfile.bib","w",encoding="utf-8") as f:
        f.write(all_bibtex)
        f.write(zenodo)
    print("\n Success! 'latex_files/bibfile.bib' has been created.")
else:
    print("\n No BibTeX entries were successfully retrieved.")


